name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup and Build
      - name: SSH key generate
        run: echo "$SSH_PRIVATE_KEY" > laract-chat_rsa && chmod 600 laract-chat_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install NPM packages
        working-directory: ./backend
        run: |
          npm i -g yarn
          yarn install

      - name: Frontend build
        working-directory: ./backend
        run: yarn production

      - name: Install Composer packages
        working-directory: ./backend
        run: php -v && composer install

      # Deployment
      - name: Frontend deploy
        working-directory: ./backend/public
        run: rsync -auzrv -e "ssh -i '$KEY' -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{secrets.SSH_PORT}}" --delete ./* "$REMOTE"
        env:
          KEY: /home/runner/work/laract-chat/laract-chat/laract-chat_rsa
          REMOTE: ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:${{secrets.SERVER_DEPLOY_DIR}}public/

      - name: Vendor deploy
        working-directory: ./backend
        run: rsync -auzrv -e "ssh -i '$KEY' -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{secrets.SSH_PORT}}" --delete ./* "$REMOTE"
        env:
          KEY: /home/runner/work/laract-chat/laract-chat/laract-chat_rsa
          REMOTE: ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:${{secrets.SERVER_DEPLOY_DIR}}vendor/

      - name: git pull By Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git checkout main
            git pull
